enchant();
var game;
window.onload = function() {
    game = new Game(640, 480);
    game.keybind(32, 'a');
    game.preload('../../../images/enchant-sphere.png');
    game.onload = function() {
        var scene = PhyScene3D();
        var camera = scene.getCamera();
        camera.x = 3;
        camera.y = 4;
        camera.z = 2;
        var tabletex = new Texture();
        tabletex.ambient = [0.8, 0.8, 0.8, 1.0];
        tabletex.diffuse = [0.1, 0.1, 0.1, 1.0];
        tabletex.specular = [0.01, 0.01, 0.01, 1.0];
        var table = new PhyBox(0.75, 0.1, 1.5, 0);
        table.rigid.rigidBody.setRestitution(0.1);
        table.mesh.setBaseColor('#446644');
        table.mesh.texture = tabletex;
        scene.addChild(table);
        var tableleft = new PhyBox(0.05, 0.1, 1.4, 0);
        tableleft.rigid.rigidBody.setRestitution(0.5);
        tableleft.mesh.setBaseColor('#664444');
        tableleft.mesh.texture = tabletex;
        tableleft.x = -0.7;
        tableleft.y = 0.2;
        scene.addChild(tableleft);
        var tableright = new PhyBox(0.05, 0.1, 1.4, 0);
        tableright.rigid.rigidBody.setRestitution(0.5);
        tableright.mesh.setBaseColor('#664444');
        tableright.mesh.texture = tabletex;
        tableright.x = 0.7;
        tableright.y = 0.2;
        scene.addChild(tableright);
        var tabletop = new PhyBox(0.75, 0.1, 0.05, 0);
        tabletop.rigid.rigidBody.setRestitution(0.5);
        tabletop.mesh.setBaseColor('#664444');
        tabletop.mesh.texture = tabletex;
        tabletop.y = 0.2;
        tabletop.z = -1.45;
        scene.addChild(tabletop);
        var tablebottom = new PhyBox(0.75, 0.1, 0.05, 0);
        tablebottom.rigid.rigidBody.setRestitution(0.5);
        tablebottom.mesh.setBaseColor('#664444');
        tablebottom.mesh.texture = tabletex;
        tablebottom.y = 0.2;
        tablebottom.z = 1.45;
        scene.addChild(tablebottom);
        var balls = new Array();

        for (var i = 0; i < ballsx.length; i++) {
            var ball = new PhySphere(0.05, 0.15);
            ball.mesh.setBaseColor(ballscolor[i]);
            ball.mesh.texture.ambient = [0.2, 0.2, 0.2, 1.0];
            ball.mesh.texture.diffuse = [0.8, 0.8, 0.8, 1.0];
            ball.mesh.texture.specular = [0.4, 0.4, 0.4, 1.0];
            ball.mesh.texture.src = game.assets['../../../images/enchant-sphere.png'];
            ball.x = ballsx[i];
            ball.y = 0.15;
            ball.z = ballsz[i];
            ball.restitution = 1.0;
            scene.addChild(ball);
        }
        var ball = new PhySphere(0.05, 0.15);
        ball.x = Math.random() * 0.1 - 0.05;
        ball.y = 0.15;
        ball.z = 0.5;
        ball.restitution = 0.6;
        ball.friction = 0.3;
        scene.addChild(ball);
        ball.addEventListener('touchend', function() {
            var args = [
                0, 0, -2.8,
                0, 0.1, 0
            ];
            this.applyImpulse.apply(this, args);
        });
        scene.play();
    };
    game.start();

};
var ballscolor = new Array();
ballscolor.push('#222222');
ballscolor.push('#222288');
ballscolor.push('#228822');
ballscolor.push('#228888');
ballscolor.push('#882222');
ballscolor.push('#882288');
ballscolor.push('#888822');
ballscolor.push('#444444');
ballscolor.push('#4444aa');
ballscolor.push('#44aa44');
ballscolor.push('#44aaaa');
ballscolor.push('#aa4444');
ballscolor.push('#aa44aa');
ballscolor.push('#aaaa44');
ballscolor.push('#aaaaaa');
var ballsx = new Array();
ballsx.push(0);
ballsx.push(-0.05);
ballsx.push(0.05);
ballsx.push(-0.1);
ballsx.push(0);
ballsx.push(0.1);
ballsx.push(-0.15);
ballsx.push(-0.05);
ballsx.push(0.05);
ballsx.push(0.15);
ballsx.push(-0.2);
ballsx.push(-0.1);
ballsx.push(0);
ballsx.push(0.1);
ballsx.push(0.2);
var ballsz = new Array();
ballsz.push(0);
ballsz.push(-0.05 * Math.sqrt(3));
ballsz.push(-0.05 * Math.sqrt(3));
ballsz.push(-0.05 * Math.sqrt(3) * 2);
ballsz.push(-0.05 * Math.sqrt(3) * 2);
ballsz.push(-0.05 * Math.sqrt(3) * 2);
ballsz.push(-0.05 * Math.sqrt(3) * 3);
ballsz.push(-0.05 * Math.sqrt(3) * 3);
ballsz.push(-0.05 * Math.sqrt(3) * 3);
ballsz.push(-0.05 * Math.sqrt(3) * 3);
ballsz.push(-0.05 * Math.sqrt(3) * 4);
ballsz.push(-0.05 * Math.sqrt(3) * 4);
ballsz.push(-0.05 * Math.sqrt(3) * 4);
ballsz.push(-0.05 * Math.sqrt(3) * 4);
ballsz.push(-0.05 * Math.sqrt(3) * 4);
